
version: '2.1'

networks:
   nginx:
    name: bridge
    external: true

services:
   sonarr:
    container_name: sonarr
    restart: unless-stopped
    ports:
     - 8004:8989
    volumes:
      - /mnt/Persistent/docker/sonarr/volume/data:/config
      - /media/devmon/EHDC/jfMedia/tvseries:/tv
      - /media/devmon/EHDC/jfMedia/downloads:/downloads
    image: linuxserver/sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Karachi
    networks:
      - nginx
