version: '2.1'

networks:
   nginx:
    name: bridge
    external: true

services:
   radarr:
    container_name: radarr
    restart: unless-stopped
    ports:
     - 8005:7878
    volumes:
      - /mnt/persistent/docker/radarr/volume/data:/config
      - /mnt/externalc/jfMedia/movies:/tv
      - /mnt/externalc/jfMedia/downloads:/downloads
    image: linuxserver/radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Karachi
    networks:
      - nginx
