version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - 8008:8080
    networks:
      - nginx


networks:
  nginx:
    name: bridge
    external: true
