version: '2.1'

networks:
  nginx:
    name: bridge
    external: true

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Karachi
    volumes:
      - /mnt/persistent/docker/jellyfin/volume/library:/config
      - /mnt/externalc/jfMedia/tvseries:/data/tvshows
      - /mnt/externalc/jfMedia/movies:/data/movies
      - /mnt/externalc/jfMedia/courses:/data/courses
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - nginx
